language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget https://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  - mysql -e "create database IF NOT EXISTS testing;" -uroot;

script:
  - vendor/bin/phpunit
